if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(ARCHITECTURE "x64")
else()
    set(ARCHITECTURE "x86")
endif()

message(STATUS "CMAKE_PRESET:                           ${CMAKE_PRESET}")
message(STATUS "CMAKE_SYSTEM_NAME:                      ${CMAKE_SYSTEM_NAME}")
message(STATUS "CMAKE_SYSTEM_PROCESSOR:                 ${CMAKE_SYSTEM_PROCESSOR}")

message(STATUS "CMAKE_C_COMPILER:                       ${CMAKE_C_COMPILER}")
message(STATUS "CMAKE_C_COMPILER_ID:                    ${CMAKE_C_COMPILER_ID}")
message(STATUS "CMAKE_C_COMPILER_VERSION:               ${CMAKE_C_COMPILER_VERSION}")
message(STATUS "CMAKE_C_COMPILER_FRONTEND_VARIANT:      ${CMAKE_C_COMPILER_FRONTEND_VARIANT}")
message(STATUS "CMAKE_CXX_COMPILER:                     ${CMAKE_CXX_COMPILER}")
message(STATUS "CMAKE_CXX_COMPILER_ID:                  ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "CMAKE_CXX_COMPILER_VERSION:             ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "CMAKE_CXX_COMPILER_FRONTEND_VARIANT:    ${CMAKE_CXX_COMPILER_FRONTEND_VARIANT}")

message(STATUS "CMAKE_SIZEOF_VOID_P:                    ${CMAKE_SIZEOF_VOID_P}")
message(STATUS "ARCHITECTURE:                           ${ARCHITECTURE}")

message(STATUS "CMAKE_BUILD_TYPE:                       ${CMAKE_BUILD_TYPE}")
message(STATUS "PROBLEM_PREFIX:                         ${PROBLEM_PREFIX}")
message(STATUS "CMAKE_INSTALL_PREFIX:                   ${CMAKE_INSTALL_PREFIX}")

message(STATUS "CMAKE_C_FLAGS_DEBUG:                    ${CMAKE_C_FLAGS_DEBUG}")
message(STATUS "CMAKE_CXX_FLAGS_DEBUG:                  ${CMAKE_CXX_FLAGS_DEBUG}")
message(STATUS "CMAKE_C_FLAGS_RELEASE:                  ${CMAKE_C_FLAGS_RELEASE}")
message(STATUS "CMAKE_CXX_FLAGS_RELEASE:                ${CMAKE_CXX_FLAGS_RELEASE}")

set(CMAKE_CONFIGURE_FILE  ${CMAKE_BINARY_DIR}/cmake_configure.conf)

message(STATUS "CMAKE_CONFIGURE_FILE:                   ${CMAKE_CONFIGURE_FILE}")
if(EXISTS "${CMAKE_CONFIGURE_FILE}")
    file(REMOVE "${CMAKE_CONFIGURE_FILE}")
endif()

file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_preset=\"${CMAKE_PRESET}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_problem_prefix=\"${PROBLEM_PREFIX}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_build_type=\"${CMAKE_BUILD_TYPE}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_generator=\"${CMAKE_GENERATOR}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_toolchain_file=\"${CMAKE_TOOLCHAIN_FILE}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_source_dir=\"${CMAKE_SOURCE_DIR}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_build_dir=\"${CMAKE_BINARY_DIR}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_install_dir=\"${CMAKE_INSTALL_PREFIX}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "ARCHITECTURE=\"${ARCHITECTURE}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_system_name=\"${CMAKE_SYSTEM_NAME}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_c_compiler=\"${CMAKE_C_COMPILER}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_c_compiler_id=\"${CMAKE_C_COMPILER_ID}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_c_compiler_version=\"${CMAKE_C_COMPILER_VERSION}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_cxx_compiler=\"${CMAKE_CXX_COMPILER}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_cxx_compiler_id=\"${CMAKE_CXX_COMPILER_ID}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_cxx_compiler_version=\"${CMAKE_CXX_COMPILER_VERSION}\"\n")
file(APPEND ${CMAKE_CONFIGURE_FILE} "cmake_system_processor=\"${CMAKE_SYSTEM_PROCESSOR}\"\n")
