if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(ARCHITECTURE "x64")
else()
    set(ARCHITECTURE "x86")
endif()

if (NOT CMAKE_PRESET)
    if (${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
        if(MSVC)
            set(CMAKE_PRESET "MSVC_${ARCHITECTURE}_${CMAKE_BUILD_TYPE}")
        elseif (MINGW)
            set(CMAKE_PRESET "Win_MinGW_${CMAKE_BUILD_TYPE}")
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            set(CMAKE_PRESET "Win_Clang_${CMAKE_BUILD_TYPE}")
        endif()
    elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
        if (CMAKE_COMPILER_IS_GNUCC)
            set(CMAKE_PRESET "Linux_GNU_${CMAKE_BUILD_TYPE}")
        elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
            set(CMAKE_PRESET "Linux_Clang_${CMAKE_BUILD_TYPE}")
        endif()
    endif()

    string(TOLOWER ${CMAKE_PRESET} CMAKE_PRESET)
endif()
